version: "3.2"

services:
  apache:
    build:
      context: './docker/apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - .env:/var/www/.env
      - ./web:/var/www/web
    container_name: apache

  php:
    build: 
      context: './docker/php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - .env:/var/www/.env
      - ./composer.json:/var/www/composer.json
      - ./composer.json:/var/www/composer.lock
      - ./config:/var/www/config:delegated
      - ./modules:/var/www/modules:cached
      - ./storage:/var/www/storage:delegated
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor:cached
      - ./web:/var/www/web
    container_name: php

  mysql:
    image: mariadb:${MYSQL_VERSION:-latest}
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./database:/var/lib/mysql:delegated
    container_name: db

networks:
  frontend:
  backend: