version: "3.2"

services:
  apache:
    build:
      context: './docker/apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/web
    container_name: apache

  php:
    build: 
      context: './docker/php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./:/var/www/
    container_name: php

  mysql:
    image: mariadb:${MYSQL_VERSION:-latest}
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./database:/var/lib/mysql
    container_name: db

networks:
  frontend:
  backend: