version: "3.2"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    links:
      - php
    container_name: nginx

  php:
    build: 
      context: './docker/php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./:/var/www/
    container_name: php

  mysql:
    image: mariadb:${MYSQL_VERSION:-latest}
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql:delegated
    container_name: db

networks:
  frontend:
  backend: